### ISSUE TITLE
Devhub SSL certificate uses deprecated key length - Warning in Chrome

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#120]
> The identity of this website has been verified by TERENA SSL CA but does not have public audit records.
> The site is using outdated security settings that may prevent future versions of Chrome from being able to safely access it.
> Your connection to devhub.ewi.tudelft.nl is encrypted with obsolete cryptography.
> The connection uses TLS 1.2.
> The connection is encrypted using AES_256_CBC, with SHA1 for message authentication and RSA as the key exchange mechanism.

![upload](https://cloud.githubusercontent.com/assets/3469492/7253540/c6d2c6a2-e83d-11e4-872d-9c1baa777e22.png)

**Comment by michaeldejong** [comment]
https://intranet.tudelft.nl/services/fmvgict-pdc/veiligheid/welkom-op-de-security-website/werk-veilig/hints-en-tips/ssl-certificaten/

**Comment by JeremybellEU** [comment]
http://googleonlinesecurity.blogspot.nl/2014/09/gradually-sunsetting-sha-1.html

**Comment by JWGmeligMeyling** [comment]
Otto fixed this issue for us.
