### ISSUE TITLE
Live feed of course events

### ISSUE THREAD

**Issue by TimvdLippe** [devhub-tud/devhub#132]
It would be nice to have a live feed of events that happen in a given course. Events that are useful for course adminstrators/assistants could be (in paranthesis possible binds to other types):
- Build failures (commit, group)
- Comments (comment, who, where)
- Group creation (who)
- Submission (assignment, group)

Essentially this is a logger that regularly updates itselves according to the information provided by the server (AJAX).

**Comment by TimvdLippe** [comment]
So we created this issue last year, because we had trouble keeping up with all the students submissions. To provide better feedback, we wanted to actively monitor their actions. Is this still something we want to do for this year?

**Comment by JWGmeligMeyling** [comment]
Yes.

**Comment by TimvdLippe** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:
