### ISSUE TITLE
Issue tracker

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#148]
See also https://github.com/devhub-tud/devhub/blob/master/src/main/java/nl/tudelft/ewi/devhub/server/database/entities/issues/AbstractIssue.java#L34 and how Pull Requests are currently handled.

**Comment by KClilBro** [comment]
How do i use the issue tracker?

**Comment by JWGmeligMeyling** [comment]
It's not in development yet.
