### ISSUE TITLE
Restructure server backend package

### ISSUE THREAD

**Issue by JeremybellEU** [devhub-tud/devhub#155]
Currently the server backend package contains 16 classes. This is quite a lot and could be divided into some sub-packages.

Proposal of division:
- BuildsBackend.java
- CoursesBackend.java
- RunnableInUnitOfWork.java
- **authentication**
  - AuthenticationBackend.java
  - AuthenticationBackednImpl.java
  - **providers**
    - AuthenticationProvider.java
    - BasicAuthenticationProvider.java
    - **ldap**
      - LdapAuthenticationProvider.java
      - LdapBackend.java
- **deliveries**
  - AssignmentStats.java
  - DeliveriesBackend.java
  - StorageBackend.java
- **projects**
  - CommentBackend.java
  - ProjectsBackend.java
  - PullRequestBackend.java
  - SshKeyBackend.java

**Comment by JWGmeligMeyling** [comment]
I agree that this should be restructured. However, I think we should go for a different hierarchy. The points that need to be addressed:

* RunnableInUnitOfWork is a utility class, it should not be in backends at all
* StorageBackend is not specific to deliveries, it should move to the root or an higher level
* AssignmentStats is just a ViewModel class for Freemarker. It's place in the backend package is really debatable. Same for the CommentCheckers
* Authentication will be changed, so we might not want to subdivide this just yet.
* We want to get rid of the term `projects`. We only have `groups` in `courses`, so I think this should be bundled in a courses backend package.
* Deliveries should go hand in hand with assignments, but there is no assignment backend yet. This should be refactored and then this should go in to an assignments package (possibly in the above noted courses package)
