### ISSUE TITLE
Can't create a pull request

### ISSUE THREAD

**Issue by LarsStegman** [devhub-tud/devhub#177]
When trying to create a pull request an exception gets thrown:

    javax.validation.ConstraintViolationException: Validation failed for classes [nl.tudelft.ewi.devhub.server.database.entities.PullRequest] during persist time for groups [javax.validation.groups.Default, ]
    List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='may not be null', propertyPath=destination, rootBeanClass=class nl.tudelft.ewi.devhub.server.database.entities.PullRequest, messageTemplate='{javax.validation.constraints.NotNull.message}'}
     ]

This text is shown in the browser.

**Comment by JWGmeligMeyling** [comment]
Please meet the TA's

**Comment by JWGmeligMeyling** [comment]
Reproducable

**Comment by JWGmeligMeyling** [comment]
Fixed now.
