### ISSUE TITLE
Long words  (or a line of characters) will overflow incorrectly in a comment

### ISSUE THREAD

**Issue by JeremybellEU** [devhub-tud/devhub#183]
![photo51325061506902540](https://cloud.githubusercontent.com/assets/5948271/7691249/57702dea-fdb9-11e4-8d54-5a48ef83fcbb.jpg)
It would probably be easiest and best to hide too long words (overflow-x: hidden;) as they rarely happen.

**Comment by JWGmeligMeyling** [comment]
```css
word-wrap: break-word;
```
on the `body > div.container > div:nth-child(3) > div.overflow-hidden > table > tbody:nth-child(1) > tr:nth-child(8) > td > div:nth-child(1) > div.panel-body` fixes this.
