### ISSUE TITLE
"Well, this is embarrassing..." when making pull request

### ISSUE THREAD

**Issue by awzang** [devhub-tud/devhub#199]
I tried to make a pull request after pushing my branch to the remote, however I got the following error message. 

![devhub_pull_request_error](https://cloud.githubusercontent.com/assets/7579804/7882029/a29942ae-0609-11e5-842d-ccb0f7b81208.PNG)

Not sure what's happening because I always follow the same procedure.
1. Make branch from master.
2. Change something.
3. Commit change.
4. Push to origin.
5. Make pull request.

**Comment by JWGmeligMeyling** [comment]
Not very descriptive error message, but your branch name is too long. We will support longer branch names soon (#191) and a more descriptive error message will be added later on (#178).
Quick fix: push your changes to a new branch with a shorter branch name.

**Comment by awzang** [comment]
What is the allowed amount of characters?

**Comment by JWGmeligMeyling** [comment]
40 including /refs/heads/ so probably 30. Also concider using dashes instead of lower dashes :smile: http://www.guyroutledge.co.uk/blog/git-branch-naming-conventions/

**Comment by awzang** [comment]
I appreciate your quick responses :) Will use the conventions, thanks.

**Comment by JWGmeligMeyling** [comment]
We now support significantly longer branch names.

**Comment by awzang** [comment]
It works :smile:
