### ISSUE TITLE
404 error upon opening pull request and commit pages.

### ISSUE THREAD

**Issue by LarsStegman** [devhub-tud/devhub#228]
Good evening,

Since a couple of days I keep getting 404 errors on multiple pages. I get them when opening the overview page of a pull request and when opening the overview of an commit. I have enclosed pictures of the errors.

We are group 6.

Opening the page on pull request 13
![schermafbeelding 2015-06-17 om 19 30 04](https://cloud.githubusercontent.com/assets/9332816/8214109/46dd4974-1527-11e5-9041-95d684f45ec3.png)

Opening the page on commit 292012dd88757c03400884d7eb90ff70cdf109e2
![schermafbeelding 2015-06-17 om 19 30 28](https://cloud.githubusercontent.com/assets/9332816/8214119/53d72e56-1527-11e5-8e5d-8f1b6357ed7a.png)

**Comment by JWGmeligMeyling** [comment]
Group number?

**Comment by LarsStegman** [comment]
6 like it says in the issue.

**Comment by JWGmeligMeyling** [comment]
Using submodules or symbolic links?

**Comment by lkroesen** [comment]
What do you mean with submodules? We don't use any symbolic links.

**Comment by JWGmeligMeyling** [comment]
No problem, I will look into the logs and report.

**Comment by LarsStegman** [comment]
Thank you!

**Comment by JWGmeligMeyling** [comment]
It seems you have broken your repository by introducing the file
```
test\200java/nl/tudelft/jpacman/game/GameTest.java
```
To the repository. (In my CLI it sometimes shows up as `test?java` and `test\java/`).

I removed the files from your repository (the correct  `src/java/nl/` version is still there).

If you have any idea how you created this file please report.

**Comment by LarsStegman** [comment]
Yeah, we wondered where that file came from. It just appeared one day and we have no idea why. Thank you for fixing it!

**Comment by JWGmeligMeyling** [comment]
Related to #236

**Comment by JWGmeligMeyling** [comment]
Not reproducible after https://github.com/devhub-tud/git-server/issues/57 .
