### ISSUE TITLE
Store open/close date for pull request

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#232]
Store close date for pull request, this can be useful for generating graphs or event feeds.

* Add column to entity
* Edit Pull request backend

**Comment by LiamClark** [comment]
Data can now be stored, it appear to be working. Any suggestions for applying this data / testing it?

**Comment by JWGmeligMeyling** [comment]
The test at https://github.com/JWGmeligMeyling/devhub/blob/new-erd/src/test/java/nl/tudelft/ewi/devhub/server/database/controllers/PullRequestsTest.java#L52 can be extended to see if the open time is indeed set on initial persist. These tests run against a real database but without the overhead of starting an entire server. Mind that simply equalling to `new Date()` may not always be correct on slower systems or platforms with different `getCurrentTimeMillis` behaviour.

The PR close is more difficult to test, because the logic currently resists in the API endpoints and therefore testing this would be pretty close to integration test. (And a correct environment is difficult to create). You can work around this by moving some logic from the resources to an backand class, and testing it against mocks.
