### ISSUE TITLE
Branches containing `/` cannot be accessed in the web client

### ISSUE THREAD

**Issue by smesseim** [devhub-tud/devhub#289]
If a branch contains `/` in its name, then that branch cannot be accessed in the web client. A 404 is returned.

**Comment by TimvdLippe** [comment]
It might be possible to escape the character? http://www.fileformat.info/info/unicode/char/2215/index.htm

**Comment by JWGmeligMeyling** [comment]
Is indeed an escaping issue. Do we have an example group?
