### ISSUE TITLE
Artifacts in submission overview

### ISSUE THREAD

**Issue by LiamClark** [devhub-tud/devhub#304]
An example:
TI1706 1516 - Software Quality & Testing (Group 10)
Lopez K**Ã¼** chlin on Wednesday 20 April 2016 15:49

instead of: Küchlin.

another:
Dani**Ã«**l 
Daniël

Possibly some character encoding problems?, not urgent at all though so this one is for the backlog

**Comment by JWGmeligMeyling** [comment]
This should also appear in the commit list, or doesn't it? I expect it to come from the conversations between the git-server and de devhub-server.

**Comment by LiamClark** [comment]
Actually in the commit list it's allright

![screen shot 2016-04-21 at 11 23 39](https://cloud.githubusercontent.com/assets/5991375/14704152/9d3f5594-07b3-11e6-8e4d-045b75e14193.png)

**Comment by JWGmeligMeyling** [comment]
Seems that it's not in the git-server indeed. Compare the two Freemarker templates:

From `project-contributers.ftl` (renders fine)
```freemarker
[#list repositoryEntity.getCollaborators() as member]
        <tr>
            <td>${member.getNetId()}</td>
            <td>${member.getName()}</td>
            <td><a href="mailto:${member.getEmail()}">${member.getEmail()}</a></td>
        </tr>
[/#list]
```

From `assignment-view.ftl`: (renders wrongly, also wrongly outputted HTML)
```freemarker
<div class="committer">${delivery.createdUser.getName()} on ${delivery.getTimestamp()?string["EEEE dd MMMM yyyy HH:mm"]}</div>
```
