### ISSUE TITLE
Folders with 1 subfolder should be collapsed in the file view

### ISSUE THREAD

**Issue by TimvdLippe** [devhub-tud/devhub#347]
When a folder has only 1 subfolder (no files) it can be truncated. E.g. `src/test/java` has 1 subfolder `nl`. Now you have to continue clicking through it, while the GitHub behavior is to directly go from `src/test` to `src/test/java/nl/...`. This saves a lot of clicks :)

**Comment by JWGmeligMeyling** [comment]
Yes I hate this as well... I still have some other stuff on my mind concerning grading and rubrics, but maybe this is a cool feature for a student to pick up :)
