### ISSUE TITLE
Long line results in overflow in line instead of on whole chunk

### ISSUE THREAD

**Issue by TimvdLippe** [devhub-tud/devhub#348]
![image](https://cloud.githubusercontent.com/assets/5948271/15161721/87024b5a-16ff-11e6-99df-afa7ffae4439.png)

I expect the whole chunk to have a scrollbar instead of just this 1 long line.

Corresponding diff:
 https://devhub.ewi.tudelft.nl/courses/ti1706/1516/groups/88/commits/afd4314543d32df61d1f15cf99f490649fa5aba0/diff/

**Comment by JWGmeligMeyling** [comment]
Yes Ive also faced this issue. Seems somewhere a CSS problem came in (maybe in our attempts to make it responsive). Will have a look at it.
