### ISSUE TITLE
Create a unit test for LargeCommitWarningGenerator

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#362]
Create a unit test for `LargeCommitWarningGenerator`, determine which dependencies to mock, which methods to stub and assess the testability of the `LargeCommitWarningGenerator`. Reflect on the code coverage improvement. Also reflect on the usefulness of the warning it produces.

**Comment by Fastjur** [comment]
Eeeuh, what happend there waffle.io? ^^^

**Comment by JWGmeligMeyling** [comment]
I believe you have to use "fixes #362" instead of "(#362)"

**Comment by Fastjur** [comment]
Hmm IIRC waffle did pick it up correctly, however I was talking about the labels
