### ISSUE TITLE
Coverage not computed due to error

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#371]
From the Travis logs
```
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.7.5.201505241946:report (default-cli) on project devhub: An error has occurred in JaCoCo Test report generation. Error while creating report: invalid entry size (expected 1377 but got 1402 bytes) -> [Help 1]
```

**Comment by stsatlantis** [comment]
Can you please tell my what was the solution?

**Comment by JWGmeligMeyling** [comment]
The Jacoco analyzer not being able to parse some resources (that were presumably git subresources)

See: https://github.com/devhub-tud/devhub/commit/c21607d753fbac1ba26e8b14d4ba84f4487620f8

And:
https://github.com/devhub-tud/devhub/tree/master/src/main/resources/static

**Comment by stsatlantis** [comment]
@JWGmeligMeyling Thanks for the fast response

**Comment by stsatlantis** [comment]
@JWGmeligMeyling Can you please answer [this question](http://stackoverflow.com/questions/32076973/error-creating-code-coverage-report-with-jacoco) as well?

**Comment by JWGmeligMeyling** [comment]
Posted the comment there, did this fix your problem as well?

**Comment by stsatlantis** [comment]
Yes luckily it did :)
