### ISSUE TITLE
When deleting non-master branch, notification mistakenly informs user that master has been deleted

### ISSUE THREAD

**Issue by jamy015** [devhub-tud/devhub#410]
When selecting a non-`master` branch in the commits overview, a button to remove that branch is present. Clicking the button correctly removes the selected branch, but a notification then incorrectly states that

> The branch master has been successfully deleted!

This bug is present regardless of whether the branch is behind or ahead of master.

**Comment by Fastjur** [comment]
Noted, I can reproduce this issue and we will fix this in the next release.

Thanks for reporting :+1:
