### ISSUE TITLE
Assignments overview for teaching assistants should list time of submission instead of due date

### ISSUE THREAD

**Issue by TimvdLippe** [devhub-tud/devhub#411]
The assignments overview for teaching assistants of the group page lists a due date, but it would be better to show the submission time of that particular submission. The deadline date I already know ;p

**Comment by Fastjur** [comment]
Is this after or before the due date of said assignment?

If it is before the due date it makes more sense to me that it shows said date, instead of your last submission.

**Comment by TimvdLippe** [comment]
After, but in both situations it feels more logical to show the timestamp of the latest submission. Now I have to perform more steps to determine the submission timestamp.

**Comment by Fastjur** [comment]
Hmm I see, after the deadline this might make sense. But I think I'd rather know when the deadline is due than when I last submitted something. I think that in any case displaying both is the best option.

**Comment by TimvdLippe** [comment]
Oh sorry I should have mentioned this request is for Teaching Assistants only. For students I would not change anything indeed!

**Comment by Fastjur** [comment]
Right, I was confused there. Could you update your issue mentioning this?

**Comment by TimvdLippe** [comment]
Ping for this years course. Would greatly reduce the amount of clicking and finding the correct values.

**Comment by JWGmeligMeyling** [comment]
My focus will be around improving the management features in Devhub and making all manual configuration unnecessary. This issue is therefore in the icebox but other collaborators are free to pick it up.

**Comment by Fastjur** [comment]
I'll assign this to myself. I'll take a look at it sometime soon

**Comment by TimvdLippe** [comment]
@Fastjur Friendly ping if soon has already passed 😄

**Comment by Fastjur** [comment]
Ah, good one. I forgot. I have some time now. I'll attempt to add it tonight!

**Comment by LiamClark** [comment]
@TimvdLippe why do you want this information in the assignment overview of a group exactly? when reviewing a specific assignment both times are being displayed.

**Comment by TimvdLippe** [comment]
It seems that the information has since be added. I can now see the submission date when reviewing a group!
