### ISSUE TITLE
Migrate rubrics from previous course edition

### ISSUE THREAD

**Issue by LiamClark** [devhub-tud/devhub#420]
When creating a new course edition it would be nice to have the rubrics of the previous course present

**Comment by LiamClark** [comment]
@JWGmeligMeyling 
We could simply add a check box so we can specifiy if we want to copy over the rubrics, however currently in create new course form it is not known if a previous edition exists. We could add this with an ajax call checking for the name the user entered, or we could maybe add a new edition for course button somewhere?

What do you prefer?

**Comment by JWGmeligMeyling** [comment]
No I wouldn't do it with course edition creation altogether, I would do it at assignment creation. There we can do: assignment > getCourseEdition > getCourse > getCourseEditions > flatMap assignments  to generate a select menu of assignments (and their assignment id's) to copy the rubrics from.
