### ISSUE TITLE
Target/metamodel keeps resetting in IntelliJ

### ISSUE THREAD

**Issue by TimvdLippe** [devhub-tud/devhub#434]
Just as a tracking issue, as far as I know @LiamClark is already looking into this.

Every time a maven dependency is changed or a maven command is run in IntelliJ, the `target/metamodel` is marked as a `resources` directory, while it should be an `generated sources root` directory.

Would be nice if this folder could be moved somewhere or if we can somehow teach IntelliJ that this folder should remain the generated sources root.

**Comment by JWGmeligMeyling** [comment]
We don't need to use a specific folder anymore, as Lombok doesn't utilise the `generated-sources` anymore and thus doesn't conflict. So we can just use `generated-sources`.

**Comment by TimvdLippe** [comment]
@LiamClark ping, you fixed this one?
