### ISSUE TITLE
Automatically set status to reviewed if reviewer did not submit a status

### ISSUE THREAD

**Issue by TimvdLippe** [devhub-tud/devhub#461]
To properly keep track of which groups are actually graded, it would be nice that once you click the submit button the status of the review changes to `reviewed` if the TA did not supply a status. This makes it easier to keep an overview of which groups still needs grading, as that is now manually checked through the list all the time.

**Comment by JWGmeligMeyling** [comment]
1) The reviewer should actually not set the status if its automatically done (eg. some rubrics may be automatically graded and then the TA may not even know the final grade)
2) Instead we should probably indicate the progress of filling in the rubrics.

**Comment by TimvdLippe** [comment]
Then please reopen this issue and then change it to "Provide a progress bar for reviewed assignments"
