### ISSUE TITLE
Display the amount of warnings and errors in a commit or part

### ISSUE THREAD

**Issue by mjwsteenbergen** [devhub-tud/devhub#462]

**Comment by Fastjur** [comment]
What errors would you want to see?

**Comment by JWGmeligMeyling** [comment]
We do display this but warnings were disabled until today.

**Comment by mjwsteenbergen** [comment]
I thought that the warnings displayed next to the commit were the new warnings generated. This is not the case, so I will close the issue.

**Comment by JWGmeligMeyling** [comment]
They do appear on the commit where the warning was generated if the line was introduced in that commit. If the line was introduced in an older commit, you should retroactively rebuild that commit. The count only shows "introduced" warnings. A disadvantage of enabling warnings relatively late, is that old warnings don't appear in the diff too. But they were enabled straight after part 1, so for entire part 2 it should be good.
