### ISSUE TITLE
Add directory name to git clone url

### ISSUE THREAD

**Issue by TimvdLippe** [devhub-tud/devhub#481]
The current clone url includes just the devhub clone url, which ends in `group-94`. To help with autocompletion for TA's (as they have a large number of local cloned repositories), it would be nice to have the directory name just as number instead. E.g. change the clone command to `git clone ssh://git@devhub.ewi.tudelft.nl/courses/ti1706/1617/group-94 94` where `94` indicates the directory that is cloned into.

**Comment by JWGmeligMeyling** [comment]
Very personal preference.
