### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by TimvdLippe** [devhub-tud/devhub#494]
I am not sure if the decision was already final, but in the case it were, I think we should archive this repository. To my knowledge, we are no longer pursuing this particular solution with any student maintainer and this repository hasn't seen any work for about a year.

**Comment by Fastjur** [comment]
I was just looking at archiving this when I saw this issue. I keep getting security scanning alerts, perhaps it is time to archive this indeed. As no one has responded on this issue I think I'll assume that it is safe to do, and archive it now :)
