### ISSUE TITLE
Ability to download files/zip of a certain commit.

### ISSUE THREAD

**Issue by maartentbm** [devhub-tud/devhub#59]
Now, it is only possible to download binary files. It would be helpful to be able to download a single (text) file or a package containing the whole project at a certain commit.

**Comment by JWGmeligMeyling** [comment]
![screen shot 2015-01-22 at 19 43 10](https://cloud.githubusercontent.com/assets/3469492/5862058/f28b1764-a26e-11e4-8c52-e1c96ce5ae61.png)
Created a download button in the [branch](https://github.com/JWGmeligMeyling/devhub/compare/git-client-refactor) that uses the new Git client.

**Comment by maartentbm** [comment]
Very nice!
