### ISSUE TITLE
Fail to build: wrong column type in DEVHUB-TEST.PUBLIC.BUILD_RESULTS for column log. Found: clob, expected: longvarchar

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#82]
When we moved to the new Hibernate ORM version, all `text` types had to be annotated with `@Lob`. In ea6cac1b46287834c226fe0a4d1ed2a7ace6dc38 the following annotation was added `@Type(type = "org.hibernate.type.TextType")`. I assume this was required to get up and running under Postgres. Using H2 however, now throws the following exception:

```
Caused by: org.hibernate.HibernateException: Wrong column type in DEVHUB-TEST.PUBLIC.BUILD_RESULTS for column log. Found: clob, expected: longvarchar
```

How should we annotate text types?

**Comment by michaeldejong** [comment]
I think we should drop H2, and start using PostgreSQL (probably in a VM).

**Comment by JWGmeligMeyling** [comment]
Good idea. I'll try to get things running under Postgres here. I will also try the `@Column(columnDefinition="text")` annotation.

**Comment by JWGmeligMeyling** [comment]
For me, neither `@Column(columnDefinition="text")` or `@Type(type = "org.hibernate.type.TextType")` seem to be required to work under Postgres `9.4.0` with the following JPA settings:
```
hibernate.dialect = org.hibernate.dialect.PostgreSQL9Dialect
hibernate.connection.driver_class = org.postgresql.Driver
javax.persistence.jdbc.url = jdbc:postgresql:devhub-test
```

**Comment by michaeldejong** [comment]
```
$ psql --version
psql (PostgreSQL) 9.4.1
```

**Comment by JWGmeligMeyling** [comment]
Curieus, nou ja.. het werkt in ieder geval.
