### ISSUE TITLE
URL of 'future' pull request causes crash

### ISSUE THREAD

**Issue by avandeursen** [devhub-tud/devhub#85]
If I guess a URL for a future pull request like

    courses/TI1705/groups/2/pull/9999

I get 

    Oops!
    Well, this is embarassing...

    Event: f0b818f9-ea89-4aaf-b50c-feba60b57da3

**Comment by JWGmeligMeyling** [comment]
This is how we currently handle NotFoundExceptions, it's the same for accessing non-existing groups/courses. We could think of a more descriptive 404 page .


Op 11 apr. 2015 om 20:33 heeft Arie van Deursen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


If I guess a URL for a future pull request like

courses/TI1705/groups/2/pull/9999


I get

Oops!
Well, this is embarassing...

Event: f0b818f9-ea89-4aaf-b50c-feba60b57da3
